### PR TITLE
Handle unexpected point orderings

### LINKED ISSUE #160: Regression on Linux
Seeing updates merged in #155 I rebuilt and tried to run on Linux.

I fired up a UFO (one that I'd just tested with the other day and was still in my command history) and double clicked on glyph. ***PANIC***.

```
thread 'main' panicked at 'index out of bounds: the len is 16 but the index is 16', src/draw.rs:206:30
```

Opening it back up and trying a few more, it seems about half of the glyphs in this particular file cause panics if I try to open them, the other half are okay. It would be a strange coincidence if testing the other day I managed not to land on any of the crashy glyphs.

### PR DESCRIPTION
**Pull request by cmyr**
This implements more careful normalization of loaded paths,
and improves documentation of how we order points in paths.

It also reworks the draw_control_point_lines method to use
path segments, which should be more robust than indexing
into the points directly.

- fixes #160

### CODE REVIEW

File: src/path.rs [hunk 1]
```diff
@@ -163,12 +177,26 @@ impl Path {
...
         id: usize,
-        points: Vec<PathPoint>,
+        mut points: Vec<PathPoint>,
         trailing: Option<DPoint>,
         closed: bool,
     ) -> Self {
         assert!(!points.is_empty(), "path may not be empty");
         assert!(points.iter().all(|pt| pt.id.parent == id), "{:#?}", points);
+        if !closed {
+            assert!(points.first().unwrap().is_on_curve());
```
Comment (raphlinus) [inline src/path.rs:187]: As a general thought, I think we should export validation errors through the UI rather than asserts. But that can be a matter for another PR.

File: src/draw.rs [hunk 2]
```diff
@@ -8,8 +8,10 @@ use crate::data::{FontMetrics, Workspace};
 use crate::design_space::ViewPort;
 use crate::edit_session::EditSession;
 use crate::guides::{Guide, GuideLine};
-use crate::path::{EntityId, Path, PointType};
-use druid::kurbo::{Affine, BezPath, Circle, CubicBez, Line, PathSeg, Point, Rect, Vec2};
+use crate::path::{EntityId, Path, PathSeg, PointType};
+use druid::kurbo::{
+    Affine, BezPath, Circle, CubicBez, Line, PathSeg as KurboPathSeg, Point, Rect, Vec2,
```
Comment (raphlinus) [inline src/draw.rs:13]: Personally I prefer importing `kurbo::self` and then saying `kurbo::PathSeg`, but that's a matter of style, certainly won't block on this.

**Review by raphlinus — APPROVED** [review]
Looks like it should fix the reported problem, thanks.

File: src/path.rs (hunk 1 above)
Comment (cmyr) [reply src/path.rs:187]: agreed; I'm just feeling a bit sketched out by some of our point-handling logic, and want to be a bit more paranoid.
